// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package org.test.web.protobuf;

public final class CustomerProtos {
  private CustomerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CustomerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.test.web.protobuf.Customer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string firstName = 2;</code>
     */
    java.lang.String getFirstName();
    /**
     * <code>optional string firstName = 2;</code>
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>optional string lastName = 3;</code>
     */
    java.lang.String getLastName();
    /**
     * <code>optional string lastName = 3;</code>
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
     */
    java.util.List<org.test.web.protobuf.CustomerProtos.Customer.EmailAddress> 
        getEmailList();
    /**
     * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
     */
    org.test.web.protobuf.CustomerProtos.Customer.EmailAddress getEmail(int index);
    /**
     * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
     */
    int getEmailCount();
    /**
     * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
     */
    java.util.List<? extends org.test.web.protobuf.CustomerProtos.Customer.EmailAddressOrBuilder> 
        getEmailOrBuilderList();
    /**
     * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
     */
    org.test.web.protobuf.CustomerProtos.Customer.EmailAddressOrBuilder getEmailOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.test.web.protobuf.Customer}
   */
  public  static final class Customer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.test.web.protobuf.Customer)
      CustomerOrBuilder {
    // Use Customer.newBuilder() to construct.
    private Customer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Customer() {
      id_ = 0;
      firstName_ = "";
      lastName_ = "";
      email_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Customer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                email_ = new java.util.ArrayList<org.test.web.protobuf.CustomerProtos.Customer.EmailAddress>();
                mutable_bitField0_ |= 0x00000008;
              }
              email_.add(
                  input.readMessage(org.test.web.protobuf.CustomerProtos.Customer.EmailAddress.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          email_ = java.util.Collections.unmodifiableList(email_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.test.web.protobuf.CustomerProtos.internal_static_org_test_web_protobuf_Customer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.test.web.protobuf.CustomerProtos.internal_static_org_test_web_protobuf_Customer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.test.web.protobuf.CustomerProtos.Customer.class, org.test.web.protobuf.CustomerProtos.Customer.Builder.class);
    }

    /**
     * Protobuf enum {@code org.test.web.protobuf.Customer.EmailType}
     */
    public enum EmailType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PRIVATE = 0;</code>
       */
      PRIVATE(0),
      /**
       * <code>PROFESSIONAL = 1;</code>
       */
      PROFESSIONAL(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>PRIVATE = 0;</code>
       */
      public static final int PRIVATE_VALUE = 0;
      /**
       * <code>PROFESSIONAL = 1;</code>
       */
      public static final int PROFESSIONAL_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EmailType valueOf(int value) {
        return forNumber(value);
      }

      public static EmailType forNumber(int value) {
        switch (value) {
          case 0: return PRIVATE;
          case 1: return PROFESSIONAL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EmailType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          EmailType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EmailType>() {
              public EmailType findValueByNumber(int number) {
                return EmailType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.test.web.protobuf.CustomerProtos.Customer.getDescriptor().getEnumTypes().get(0);
      }

      private static final EmailType[] VALUES = values();

      public static EmailType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private EmailType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.test.web.protobuf.Customer.EmailType)
    }

    public interface EmailAddressOrBuilder extends
        // @@protoc_insertion_point(interface_extends:org.test.web.protobuf.Customer.EmailAddress)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string email = 1;</code>
       */
      java.lang.String getEmail();
      /**
       * <code>optional string email = 1;</code>
       */
      com.google.protobuf.ByteString
          getEmailBytes();

      /**
       * <code>optional .org.test.web.protobuf.Customer.EmailType type = 2;</code>
       */
      int getTypeValue();
      /**
       * <code>optional .org.test.web.protobuf.Customer.EmailType type = 2;</code>
       */
      org.test.web.protobuf.CustomerProtos.Customer.EmailType getType();
    }
    /**
     * Protobuf type {@code org.test.web.protobuf.Customer.EmailAddress}
     */
    public  static final class EmailAddress extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:org.test.web.protobuf.Customer.EmailAddress)
        EmailAddressOrBuilder {
      // Use EmailAddress.newBuilder() to construct.
      private EmailAddress(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private EmailAddress() {
        email_ = "";
        type_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private EmailAddress(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                email_ = s;
                break;
              }
              case 16: {
                int rawValue = input.readEnum();

                type_ = rawValue;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.test.web.protobuf.CustomerProtos.internal_static_org_test_web_protobuf_Customer_EmailAddress_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.test.web.protobuf.CustomerProtos.internal_static_org_test_web_protobuf_Customer_EmailAddress_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.test.web.protobuf.CustomerProtos.Customer.EmailAddress.class, org.test.web.protobuf.CustomerProtos.Customer.EmailAddress.Builder.class);
      }

      public static final int EMAIL_FIELD_NUMBER = 1;
      private volatile java.lang.Object email_;
      /**
       * <code>optional string email = 1;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        }
      }
      /**
       * <code>optional string email = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TYPE_FIELD_NUMBER = 2;
      private int type_;
      /**
       * <code>optional .org.test.web.protobuf.Customer.EmailType type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .org.test.web.protobuf.Customer.EmailType type = 2;</code>
       */
      public org.test.web.protobuf.CustomerProtos.Customer.EmailType getType() {
        org.test.web.protobuf.CustomerProtos.Customer.EmailType result = org.test.web.protobuf.CustomerProtos.Customer.EmailType.valueOf(type_);
        return result == null ? org.test.web.protobuf.CustomerProtos.Customer.EmailType.UNRECOGNIZED : result;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getEmailBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, email_);
        }
        if (type_ != org.test.web.protobuf.CustomerProtos.Customer.EmailType.PRIVATE.getNumber()) {
          output.writeEnum(2, type_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getEmailBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, email_);
        }
        if (type_ != org.test.web.protobuf.CustomerProtos.Customer.EmailType.PRIVATE.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, type_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof org.test.web.protobuf.CustomerProtos.Customer.EmailAddress)) {
          return super.equals(obj);
        }
        org.test.web.protobuf.CustomerProtos.Customer.EmailAddress other = (org.test.web.protobuf.CustomerProtos.Customer.EmailAddress) obj;

        boolean result = true;
        result = result && getEmail()
            .equals(other.getEmail());
        result = result && type_ == other.type_;
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + EMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getEmail().hashCode();
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static org.test.web.protobuf.CustomerProtos.Customer.EmailAddress parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.test.web.protobuf.CustomerProtos.Customer.EmailAddress parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.test.web.protobuf.CustomerProtos.Customer.EmailAddress parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.test.web.protobuf.CustomerProtos.Customer.EmailAddress parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.test.web.protobuf.CustomerProtos.Customer.EmailAddress parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.test.web.protobuf.CustomerProtos.Customer.EmailAddress parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.test.web.protobuf.CustomerProtos.Customer.EmailAddress parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static org.test.web.protobuf.CustomerProtos.Customer.EmailAddress parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.test.web.protobuf.CustomerProtos.Customer.EmailAddress parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.test.web.protobuf.CustomerProtos.Customer.EmailAddress parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(org.test.web.protobuf.CustomerProtos.Customer.EmailAddress prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code org.test.web.protobuf.Customer.EmailAddress}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:org.test.web.protobuf.Customer.EmailAddress)
          org.test.web.protobuf.CustomerProtos.Customer.EmailAddressOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.test.web.protobuf.CustomerProtos.internal_static_org_test_web_protobuf_Customer_EmailAddress_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.test.web.protobuf.CustomerProtos.internal_static_org_test_web_protobuf_Customer_EmailAddress_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.test.web.protobuf.CustomerProtos.Customer.EmailAddress.class, org.test.web.protobuf.CustomerProtos.Customer.EmailAddress.Builder.class);
        }

        // Construct using org.test.web.protobuf.CustomerProtos.Customer.EmailAddress.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          email_ = "";

          type_ = 0;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.test.web.protobuf.CustomerProtos.internal_static_org_test_web_protobuf_Customer_EmailAddress_descriptor;
        }

        public org.test.web.protobuf.CustomerProtos.Customer.EmailAddress getDefaultInstanceForType() {
          return org.test.web.protobuf.CustomerProtos.Customer.EmailAddress.getDefaultInstance();
        }

        public org.test.web.protobuf.CustomerProtos.Customer.EmailAddress build() {
          org.test.web.protobuf.CustomerProtos.Customer.EmailAddress result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public org.test.web.protobuf.CustomerProtos.Customer.EmailAddress buildPartial() {
          org.test.web.protobuf.CustomerProtos.Customer.EmailAddress result = new org.test.web.protobuf.CustomerProtos.Customer.EmailAddress(this);
          result.email_ = email_;
          result.type_ = type_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.test.web.protobuf.CustomerProtos.Customer.EmailAddress) {
            return mergeFrom((org.test.web.protobuf.CustomerProtos.Customer.EmailAddress)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.test.web.protobuf.CustomerProtos.Customer.EmailAddress other) {
          if (other == org.test.web.protobuf.CustomerProtos.Customer.EmailAddress.getDefaultInstance()) return this;
          if (!other.getEmail().isEmpty()) {
            email_ = other.email_;
            onChanged();
          }
          if (other.type_ != 0) {
            setTypeValue(other.getTypeValue());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.test.web.protobuf.CustomerProtos.Customer.EmailAddress parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.test.web.protobuf.CustomerProtos.Customer.EmailAddress) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object email_ = "";
        /**
         * <code>optional string email = 1;</code>
         */
        public java.lang.String getEmail() {
          java.lang.Object ref = email_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            email_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string email = 1;</code>
         */
        public com.google.protobuf.ByteString
            getEmailBytes() {
          java.lang.Object ref = email_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            email_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string email = 1;</code>
         */
        public Builder setEmail(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          email_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string email = 1;</code>
         */
        public Builder clearEmail() {
          
          email_ = getDefaultInstance().getEmail();
          onChanged();
          return this;
        }
        /**
         * <code>optional string email = 1;</code>
         */
        public Builder setEmailBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          email_ = value;
          onChanged();
          return this;
        }

        private int type_ = 0;
        /**
         * <code>optional .org.test.web.protobuf.Customer.EmailType type = 2;</code>
         */
        public int getTypeValue() {
          return type_;
        }
        /**
         * <code>optional .org.test.web.protobuf.Customer.EmailType type = 2;</code>
         */
        public Builder setTypeValue(int value) {
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .org.test.web.protobuf.Customer.EmailType type = 2;</code>
         */
        public org.test.web.protobuf.CustomerProtos.Customer.EmailType getType() {
          org.test.web.protobuf.CustomerProtos.Customer.EmailType result = org.test.web.protobuf.CustomerProtos.Customer.EmailType.valueOf(type_);
          return result == null ? org.test.web.protobuf.CustomerProtos.Customer.EmailType.UNRECOGNIZED : result;
        }
        /**
         * <code>optional .org.test.web.protobuf.Customer.EmailType type = 2;</code>
         */
        public Builder setType(org.test.web.protobuf.CustomerProtos.Customer.EmailType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          type_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>optional .org.test.web.protobuf.Customer.EmailType type = 2;</code>
         */
        public Builder clearType() {
          
          type_ = 0;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:org.test.web.protobuf.Customer.EmailAddress)
      }

      // @@protoc_insertion_point(class_scope:org.test.web.protobuf.Customer.EmailAddress)
      private static final org.test.web.protobuf.CustomerProtos.Customer.EmailAddress DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new org.test.web.protobuf.CustomerProtos.Customer.EmailAddress();
      }

      public static org.test.web.protobuf.CustomerProtos.Customer.EmailAddress getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<EmailAddress>
          PARSER = new com.google.protobuf.AbstractParser<EmailAddress>() {
        public EmailAddress parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new EmailAddress(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<EmailAddress> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<EmailAddress> getParserForType() {
        return PARSER;
      }

      public org.test.web.protobuf.CustomerProtos.Customer.EmailAddress getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int FIRSTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object firstName_;
    /**
     * <code>optional string firstName = 2;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string firstName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object lastName_;
    /**
     * <code>optional string lastName = 3;</code>
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string lastName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 5;
    private java.util.List<org.test.web.protobuf.CustomerProtos.Customer.EmailAddress> email_;
    /**
     * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
     */
    public java.util.List<org.test.web.protobuf.CustomerProtos.Customer.EmailAddress> getEmailList() {
      return email_;
    }
    /**
     * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
     */
    public java.util.List<? extends org.test.web.protobuf.CustomerProtos.Customer.EmailAddressOrBuilder> 
        getEmailOrBuilderList() {
      return email_;
    }
    /**
     * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
     */
    public int getEmailCount() {
      return email_.size();
    }
    /**
     * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
     */
    public org.test.web.protobuf.CustomerProtos.Customer.EmailAddress getEmail(int index) {
      return email_.get(index);
    }
    /**
     * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
     */
    public org.test.web.protobuf.CustomerProtos.Customer.EmailAddressOrBuilder getEmailOrBuilder(
        int index) {
      return email_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
      }
      for (int i = 0; i < email_.size(); i++) {
        output.writeMessage(5, email_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
      }
      for (int i = 0; i < email_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, email_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.test.web.protobuf.CustomerProtos.Customer)) {
        return super.equals(obj);
      }
      org.test.web.protobuf.CustomerProtos.Customer other = (org.test.web.protobuf.CustomerProtos.Customer) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getFirstName()
          .equals(other.getFirstName());
      result = result && getLastName()
          .equals(other.getLastName());
      result = result && getEmailList()
          .equals(other.getEmailList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      if (getEmailCount() > 0) {
        hash = (37 * hash) + EMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getEmailList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.test.web.protobuf.CustomerProtos.Customer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.test.web.protobuf.CustomerProtos.Customer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.test.web.protobuf.CustomerProtos.Customer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.test.web.protobuf.CustomerProtos.Customer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.test.web.protobuf.CustomerProtos.Customer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.test.web.protobuf.CustomerProtos.Customer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.test.web.protobuf.CustomerProtos.Customer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.test.web.protobuf.CustomerProtos.Customer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.test.web.protobuf.CustomerProtos.Customer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.test.web.protobuf.CustomerProtos.Customer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.test.web.protobuf.CustomerProtos.Customer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.test.web.protobuf.Customer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.test.web.protobuf.Customer)
        org.test.web.protobuf.CustomerProtos.CustomerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.test.web.protobuf.CustomerProtos.internal_static_org_test_web_protobuf_Customer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.test.web.protobuf.CustomerProtos.internal_static_org_test_web_protobuf_Customer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.test.web.protobuf.CustomerProtos.Customer.class, org.test.web.protobuf.CustomerProtos.Customer.Builder.class);
      }

      // Construct using org.test.web.protobuf.CustomerProtos.Customer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEmailFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        firstName_ = "";

        lastName_ = "";

        if (emailBuilder_ == null) {
          email_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          emailBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.test.web.protobuf.CustomerProtos.internal_static_org_test_web_protobuf_Customer_descriptor;
      }

      public org.test.web.protobuf.CustomerProtos.Customer getDefaultInstanceForType() {
        return org.test.web.protobuf.CustomerProtos.Customer.getDefaultInstance();
      }

      public org.test.web.protobuf.CustomerProtos.Customer build() {
        org.test.web.protobuf.CustomerProtos.Customer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.test.web.protobuf.CustomerProtos.Customer buildPartial() {
        org.test.web.protobuf.CustomerProtos.Customer result = new org.test.web.protobuf.CustomerProtos.Customer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        if (emailBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            email_ = java.util.Collections.unmodifiableList(email_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.email_ = email_;
        } else {
          result.email_ = emailBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.test.web.protobuf.CustomerProtos.Customer) {
          return mergeFrom((org.test.web.protobuf.CustomerProtos.Customer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.test.web.protobuf.CustomerProtos.Customer other) {
        if (other == org.test.web.protobuf.CustomerProtos.Customer.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (emailBuilder_ == null) {
          if (!other.email_.isEmpty()) {
            if (email_.isEmpty()) {
              email_ = other.email_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureEmailIsMutable();
              email_.addAll(other.email_);
            }
            onChanged();
          }
        } else {
          if (!other.email_.isEmpty()) {
            if (emailBuilder_.isEmpty()) {
              emailBuilder_.dispose();
              emailBuilder_ = null;
              email_ = other.email_;
              bitField0_ = (bitField0_ & ~0x00000008);
              emailBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEmailFieldBuilder() : null;
            } else {
              emailBuilder_.addAllMessages(other.email_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.test.web.protobuf.CustomerProtos.Customer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.test.web.protobuf.CustomerProtos.Customer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>optional string firstName = 2;</code>
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string firstName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string firstName = 2;</code>
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string firstName = 2;</code>
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string firstName = 2;</code>
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>optional string lastName = 3;</code>
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string lastName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string lastName = 3;</code>
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string lastName = 3;</code>
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string lastName = 3;</code>
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private java.util.List<org.test.web.protobuf.CustomerProtos.Customer.EmailAddress> email_ =
        java.util.Collections.emptyList();
      private void ensureEmailIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          email_ = new java.util.ArrayList<org.test.web.protobuf.CustomerProtos.Customer.EmailAddress>(email_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.test.web.protobuf.CustomerProtos.Customer.EmailAddress, org.test.web.protobuf.CustomerProtos.Customer.EmailAddress.Builder, org.test.web.protobuf.CustomerProtos.Customer.EmailAddressOrBuilder> emailBuilder_;

      /**
       * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
       */
      public java.util.List<org.test.web.protobuf.CustomerProtos.Customer.EmailAddress> getEmailList() {
        if (emailBuilder_ == null) {
          return java.util.Collections.unmodifiableList(email_);
        } else {
          return emailBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
       */
      public int getEmailCount() {
        if (emailBuilder_ == null) {
          return email_.size();
        } else {
          return emailBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
       */
      public org.test.web.protobuf.CustomerProtos.Customer.EmailAddress getEmail(int index) {
        if (emailBuilder_ == null) {
          return email_.get(index);
        } else {
          return emailBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
       */
      public Builder setEmail(
          int index, org.test.web.protobuf.CustomerProtos.Customer.EmailAddress value) {
        if (emailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmailIsMutable();
          email_.set(index, value);
          onChanged();
        } else {
          emailBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
       */
      public Builder setEmail(
          int index, org.test.web.protobuf.CustomerProtos.Customer.EmailAddress.Builder builderForValue) {
        if (emailBuilder_ == null) {
          ensureEmailIsMutable();
          email_.set(index, builderForValue.build());
          onChanged();
        } else {
          emailBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
       */
      public Builder addEmail(org.test.web.protobuf.CustomerProtos.Customer.EmailAddress value) {
        if (emailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmailIsMutable();
          email_.add(value);
          onChanged();
        } else {
          emailBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
       */
      public Builder addEmail(
          int index, org.test.web.protobuf.CustomerProtos.Customer.EmailAddress value) {
        if (emailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmailIsMutable();
          email_.add(index, value);
          onChanged();
        } else {
          emailBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
       */
      public Builder addEmail(
          org.test.web.protobuf.CustomerProtos.Customer.EmailAddress.Builder builderForValue) {
        if (emailBuilder_ == null) {
          ensureEmailIsMutable();
          email_.add(builderForValue.build());
          onChanged();
        } else {
          emailBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
       */
      public Builder addEmail(
          int index, org.test.web.protobuf.CustomerProtos.Customer.EmailAddress.Builder builderForValue) {
        if (emailBuilder_ == null) {
          ensureEmailIsMutable();
          email_.add(index, builderForValue.build());
          onChanged();
        } else {
          emailBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
       */
      public Builder addAllEmail(
          java.lang.Iterable<? extends org.test.web.protobuf.CustomerProtos.Customer.EmailAddress> values) {
        if (emailBuilder_ == null) {
          ensureEmailIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, email_);
          onChanged();
        } else {
          emailBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
       */
      public Builder clearEmail() {
        if (emailBuilder_ == null) {
          email_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          emailBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
       */
      public Builder removeEmail(int index) {
        if (emailBuilder_ == null) {
          ensureEmailIsMutable();
          email_.remove(index);
          onChanged();
        } else {
          emailBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
       */
      public org.test.web.protobuf.CustomerProtos.Customer.EmailAddress.Builder getEmailBuilder(
          int index) {
        return getEmailFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
       */
      public org.test.web.protobuf.CustomerProtos.Customer.EmailAddressOrBuilder getEmailOrBuilder(
          int index) {
        if (emailBuilder_ == null) {
          return email_.get(index);  } else {
          return emailBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
       */
      public java.util.List<? extends org.test.web.protobuf.CustomerProtos.Customer.EmailAddressOrBuilder> 
           getEmailOrBuilderList() {
        if (emailBuilder_ != null) {
          return emailBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(email_);
        }
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
       */
      public org.test.web.protobuf.CustomerProtos.Customer.EmailAddress.Builder addEmailBuilder() {
        return getEmailFieldBuilder().addBuilder(
            org.test.web.protobuf.CustomerProtos.Customer.EmailAddress.getDefaultInstance());
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
       */
      public org.test.web.protobuf.CustomerProtos.Customer.EmailAddress.Builder addEmailBuilder(
          int index) {
        return getEmailFieldBuilder().addBuilder(
            index, org.test.web.protobuf.CustomerProtos.Customer.EmailAddress.getDefaultInstance());
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer.EmailAddress email = 5;</code>
       */
      public java.util.List<org.test.web.protobuf.CustomerProtos.Customer.EmailAddress.Builder> 
           getEmailBuilderList() {
        return getEmailFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.test.web.protobuf.CustomerProtos.Customer.EmailAddress, org.test.web.protobuf.CustomerProtos.Customer.EmailAddress.Builder, org.test.web.protobuf.CustomerProtos.Customer.EmailAddressOrBuilder> 
          getEmailFieldBuilder() {
        if (emailBuilder_ == null) {
          emailBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.test.web.protobuf.CustomerProtos.Customer.EmailAddress, org.test.web.protobuf.CustomerProtos.Customer.EmailAddress.Builder, org.test.web.protobuf.CustomerProtos.Customer.EmailAddressOrBuilder>(
                  email_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          email_ = null;
        }
        return emailBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.test.web.protobuf.Customer)
    }

    // @@protoc_insertion_point(class_scope:org.test.web.protobuf.Customer)
    private static final org.test.web.protobuf.CustomerProtos.Customer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.test.web.protobuf.CustomerProtos.Customer();
    }

    public static org.test.web.protobuf.CustomerProtos.Customer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Customer>
        PARSER = new com.google.protobuf.AbstractParser<Customer>() {
      public Customer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Customer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Customer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Customer> getParserForType() {
      return PARSER;
    }

    public org.test.web.protobuf.CustomerProtos.Customer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OrganizationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.test.web.protobuf.Organization)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
     */
    java.util.List<org.test.web.protobuf.CustomerProtos.Customer> 
        getCustomerList();
    /**
     * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
     */
    org.test.web.protobuf.CustomerProtos.Customer getCustomer(int index);
    /**
     * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
     */
    int getCustomerCount();
    /**
     * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
     */
    java.util.List<? extends org.test.web.protobuf.CustomerProtos.CustomerOrBuilder> 
        getCustomerOrBuilderList();
    /**
     * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
     */
    org.test.web.protobuf.CustomerProtos.CustomerOrBuilder getCustomerOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.test.web.protobuf.Organization}
   */
  public  static final class Organization extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.test.web.protobuf.Organization)
      OrganizationOrBuilder {
    // Use Organization.newBuilder() to construct.
    private Organization(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Organization() {
      name_ = "";
      customer_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Organization(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                customer_ = new java.util.ArrayList<org.test.web.protobuf.CustomerProtos.Customer>();
                mutable_bitField0_ |= 0x00000002;
              }
              customer_.add(
                  input.readMessage(org.test.web.protobuf.CustomerProtos.Customer.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          customer_ = java.util.Collections.unmodifiableList(customer_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.test.web.protobuf.CustomerProtos.internal_static_org_test_web_protobuf_Organization_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.test.web.protobuf.CustomerProtos.internal_static_org_test_web_protobuf_Organization_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.test.web.protobuf.CustomerProtos.Organization.class, org.test.web.protobuf.CustomerProtos.Organization.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUSTOMER_FIELD_NUMBER = 2;
    private java.util.List<org.test.web.protobuf.CustomerProtos.Customer> customer_;
    /**
     * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
     */
    public java.util.List<org.test.web.protobuf.CustomerProtos.Customer> getCustomerList() {
      return customer_;
    }
    /**
     * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
     */
    public java.util.List<? extends org.test.web.protobuf.CustomerProtos.CustomerOrBuilder> 
        getCustomerOrBuilderList() {
      return customer_;
    }
    /**
     * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
     */
    public int getCustomerCount() {
      return customer_.size();
    }
    /**
     * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
     */
    public org.test.web.protobuf.CustomerProtos.Customer getCustomer(int index) {
      return customer_.get(index);
    }
    /**
     * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
     */
    public org.test.web.protobuf.CustomerProtos.CustomerOrBuilder getCustomerOrBuilder(
        int index) {
      return customer_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      for (int i = 0; i < customer_.size(); i++) {
        output.writeMessage(2, customer_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      for (int i = 0; i < customer_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, customer_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.test.web.protobuf.CustomerProtos.Organization)) {
        return super.equals(obj);
      }
      org.test.web.protobuf.CustomerProtos.Organization other = (org.test.web.protobuf.CustomerProtos.Organization) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && getCustomerList()
          .equals(other.getCustomerList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getCustomerCount() > 0) {
        hash = (37 * hash) + CUSTOMER_FIELD_NUMBER;
        hash = (53 * hash) + getCustomerList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.test.web.protobuf.CustomerProtos.Organization parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.test.web.protobuf.CustomerProtos.Organization parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.test.web.protobuf.CustomerProtos.Organization parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.test.web.protobuf.CustomerProtos.Organization parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.test.web.protobuf.CustomerProtos.Organization parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.test.web.protobuf.CustomerProtos.Organization parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.test.web.protobuf.CustomerProtos.Organization parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.test.web.protobuf.CustomerProtos.Organization parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.test.web.protobuf.CustomerProtos.Organization parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.test.web.protobuf.CustomerProtos.Organization parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.test.web.protobuf.CustomerProtos.Organization prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.test.web.protobuf.Organization}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.test.web.protobuf.Organization)
        org.test.web.protobuf.CustomerProtos.OrganizationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.test.web.protobuf.CustomerProtos.internal_static_org_test_web_protobuf_Organization_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.test.web.protobuf.CustomerProtos.internal_static_org_test_web_protobuf_Organization_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.test.web.protobuf.CustomerProtos.Organization.class, org.test.web.protobuf.CustomerProtos.Organization.Builder.class);
      }

      // Construct using org.test.web.protobuf.CustomerProtos.Organization.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCustomerFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        if (customerBuilder_ == null) {
          customer_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          customerBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.test.web.protobuf.CustomerProtos.internal_static_org_test_web_protobuf_Organization_descriptor;
      }

      public org.test.web.protobuf.CustomerProtos.Organization getDefaultInstanceForType() {
        return org.test.web.protobuf.CustomerProtos.Organization.getDefaultInstance();
      }

      public org.test.web.protobuf.CustomerProtos.Organization build() {
        org.test.web.protobuf.CustomerProtos.Organization result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.test.web.protobuf.CustomerProtos.Organization buildPartial() {
        org.test.web.protobuf.CustomerProtos.Organization result = new org.test.web.protobuf.CustomerProtos.Organization(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        if (customerBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            customer_ = java.util.Collections.unmodifiableList(customer_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.customer_ = customer_;
        } else {
          result.customer_ = customerBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.test.web.protobuf.CustomerProtos.Organization) {
          return mergeFrom((org.test.web.protobuf.CustomerProtos.Organization)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.test.web.protobuf.CustomerProtos.Organization other) {
        if (other == org.test.web.protobuf.CustomerProtos.Organization.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (customerBuilder_ == null) {
          if (!other.customer_.isEmpty()) {
            if (customer_.isEmpty()) {
              customer_ = other.customer_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureCustomerIsMutable();
              customer_.addAll(other.customer_);
            }
            onChanged();
          }
        } else {
          if (!other.customer_.isEmpty()) {
            if (customerBuilder_.isEmpty()) {
              customerBuilder_.dispose();
              customerBuilder_ = null;
              customer_ = other.customer_;
              bitField0_ = (bitField0_ & ~0x00000002);
              customerBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCustomerFieldBuilder() : null;
            } else {
              customerBuilder_.addAllMessages(other.customer_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.test.web.protobuf.CustomerProtos.Organization parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.test.web.protobuf.CustomerProtos.Organization) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<org.test.web.protobuf.CustomerProtos.Customer> customer_ =
        java.util.Collections.emptyList();
      private void ensureCustomerIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          customer_ = new java.util.ArrayList<org.test.web.protobuf.CustomerProtos.Customer>(customer_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.test.web.protobuf.CustomerProtos.Customer, org.test.web.protobuf.CustomerProtos.Customer.Builder, org.test.web.protobuf.CustomerProtos.CustomerOrBuilder> customerBuilder_;

      /**
       * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
       */
      public java.util.List<org.test.web.protobuf.CustomerProtos.Customer> getCustomerList() {
        if (customerBuilder_ == null) {
          return java.util.Collections.unmodifiableList(customer_);
        } else {
          return customerBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
       */
      public int getCustomerCount() {
        if (customerBuilder_ == null) {
          return customer_.size();
        } else {
          return customerBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
       */
      public org.test.web.protobuf.CustomerProtos.Customer getCustomer(int index) {
        if (customerBuilder_ == null) {
          return customer_.get(index);
        } else {
          return customerBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
       */
      public Builder setCustomer(
          int index, org.test.web.protobuf.CustomerProtos.Customer value) {
        if (customerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomerIsMutable();
          customer_.set(index, value);
          onChanged();
        } else {
          customerBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
       */
      public Builder setCustomer(
          int index, org.test.web.protobuf.CustomerProtos.Customer.Builder builderForValue) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          customer_.set(index, builderForValue.build());
          onChanged();
        } else {
          customerBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
       */
      public Builder addCustomer(org.test.web.protobuf.CustomerProtos.Customer value) {
        if (customerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomerIsMutable();
          customer_.add(value);
          onChanged();
        } else {
          customerBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
       */
      public Builder addCustomer(
          int index, org.test.web.protobuf.CustomerProtos.Customer value) {
        if (customerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomerIsMutable();
          customer_.add(index, value);
          onChanged();
        } else {
          customerBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
       */
      public Builder addCustomer(
          org.test.web.protobuf.CustomerProtos.Customer.Builder builderForValue) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          customer_.add(builderForValue.build());
          onChanged();
        } else {
          customerBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
       */
      public Builder addCustomer(
          int index, org.test.web.protobuf.CustomerProtos.Customer.Builder builderForValue) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          customer_.add(index, builderForValue.build());
          onChanged();
        } else {
          customerBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
       */
      public Builder addAllCustomer(
          java.lang.Iterable<? extends org.test.web.protobuf.CustomerProtos.Customer> values) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, customer_);
          onChanged();
        } else {
          customerBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
       */
      public Builder clearCustomer() {
        if (customerBuilder_ == null) {
          customer_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          customerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
       */
      public Builder removeCustomer(int index) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          customer_.remove(index);
          onChanged();
        } else {
          customerBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
       */
      public org.test.web.protobuf.CustomerProtos.Customer.Builder getCustomerBuilder(
          int index) {
        return getCustomerFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
       */
      public org.test.web.protobuf.CustomerProtos.CustomerOrBuilder getCustomerOrBuilder(
          int index) {
        if (customerBuilder_ == null) {
          return customer_.get(index);  } else {
          return customerBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
       */
      public java.util.List<? extends org.test.web.protobuf.CustomerProtos.CustomerOrBuilder> 
           getCustomerOrBuilderList() {
        if (customerBuilder_ != null) {
          return customerBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(customer_);
        }
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
       */
      public org.test.web.protobuf.CustomerProtos.Customer.Builder addCustomerBuilder() {
        return getCustomerFieldBuilder().addBuilder(
            org.test.web.protobuf.CustomerProtos.Customer.getDefaultInstance());
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
       */
      public org.test.web.protobuf.CustomerProtos.Customer.Builder addCustomerBuilder(
          int index) {
        return getCustomerFieldBuilder().addBuilder(
            index, org.test.web.protobuf.CustomerProtos.Customer.getDefaultInstance());
      }
      /**
       * <code>repeated .org.test.web.protobuf.Customer customer = 2;</code>
       */
      public java.util.List<org.test.web.protobuf.CustomerProtos.Customer.Builder> 
           getCustomerBuilderList() {
        return getCustomerFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.test.web.protobuf.CustomerProtos.Customer, org.test.web.protobuf.CustomerProtos.Customer.Builder, org.test.web.protobuf.CustomerProtos.CustomerOrBuilder> 
          getCustomerFieldBuilder() {
        if (customerBuilder_ == null) {
          customerBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.test.web.protobuf.CustomerProtos.Customer, org.test.web.protobuf.CustomerProtos.Customer.Builder, org.test.web.protobuf.CustomerProtos.CustomerOrBuilder>(
                  customer_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          customer_ = null;
        }
        return customerBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.test.web.protobuf.Organization)
    }

    // @@protoc_insertion_point(class_scope:org.test.web.protobuf.Organization)
    private static final org.test.web.protobuf.CustomerProtos.Organization DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.test.web.protobuf.CustomerProtos.Organization();
    }

    public static org.test.web.protobuf.CustomerProtos.Organization getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Organization>
        PARSER = new com.google.protobuf.AbstractParser<Organization>() {
      public Organization parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Organization(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Organization> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Organization> getParserForType() {
      return PARSER;
    }

    public org.test.web.protobuf.CustomerProtos.Organization getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_test_web_protobuf_Customer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_test_web_protobuf_Customer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_test_web_protobuf_Customer_EmailAddress_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_test_web_protobuf_Customer_EmailAddress_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_test_web_protobuf_Organization_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_test_web_protobuf_Organization_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016customer.proto\022\025org.test.web.protobuf\"" +
      "\374\001\n\010Customer\022\n\n\002id\030\001 \001(\005\022\021\n\tfirstName\030\002 " +
      "\001(\t\022\020\n\010lastName\030\003 \001(\t\022;\n\005email\030\005 \003(\0132,.o" +
      "rg.test.web.protobuf.Customer.EmailAddre" +
      "ss\032V\n\014EmailAddress\022\r\n\005email\030\001 \001(\t\0227\n\004typ" +
      "e\030\002 \001(\0162).org.test.web.protobuf.Customer" +
      ".EmailType\"*\n\tEmailType\022\013\n\007PRIVATE\020\000\022\020\n\014" +
      "PROFESSIONAL\020\001\"O\n\014Organization\022\014\n\004name\030\001" +
      " \001(\t\0221\n\010customer\030\002 \003(\0132\037.org.test.web.pr" +
      "otobuf.CustomerB\'\n\025org.test.web.protobuf",
      "B\016CustomerProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_test_web_protobuf_Customer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_test_web_protobuf_Customer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_test_web_protobuf_Customer_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "Email", });
    internal_static_org_test_web_protobuf_Customer_EmailAddress_descriptor =
      internal_static_org_test_web_protobuf_Customer_descriptor.getNestedTypes().get(0);
    internal_static_org_test_web_protobuf_Customer_EmailAddress_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_test_web_protobuf_Customer_EmailAddress_descriptor,
        new java.lang.String[] { "Email", "Type", });
    internal_static_org_test_web_protobuf_Organization_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_test_web_protobuf_Organization_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_test_web_protobuf_Organization_descriptor,
        new java.lang.String[] { "Name", "Customer", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
